name: Build and Push Microservices

on:
  push:
    branches:
      - master  # Adjust the branch you want to trigger this workflow

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
        if: success()

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        if: success()
      
      

      - name: Build and push images
        run: |
          for service in adservice cartservice checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice; do
            cd src
            cd $service
            docker buildx build --platform linux/amd64,linux/arm64 -t ristabel/$service:latest -f Dockerfile . --push
            cd ..
          done
        if: success()
      
      - name: Build cartservice
        run: |
            cd src/cartservice/src
            docker buildx build --platform linux/amd64,linux/arm64 -t ristabel/cartservice:latest -f Dockerfile . --push
            cd ..
        if: success()

